spring:
  datasource:
    url: jdbc:h2:mem:mydb;NON_KEYWORDS=user,name,user;
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  liquibase:
    change-log: classpath:/liquibase/changelog.yml
server:
  port: 8086

icon:
  app:
    jwtCookieName: icon
    jwtSecret: ======================iconsecret=Spring===========================
    jwtExpirationMs: 86400000